package upgrad;

import com.mongodb.client.*;
import org.bson.Document;

import java.sql.*;

public class Driver {

    /**
     * Driver class main method
     * @param args
     * @throws SQLException
     */
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:mysql://pgc-sd-bigdata.cyaielc9bmnf.us-east-1.rds.amazonaws.com:3306/pgcdata";
        String user = "student";
        String password = "STUDENT123";

        // Mongodb configuration
        String noSqlDBName = "upgrad";
        String mongoConnectionString = "mongodb://ec2-3-239-59-208.compute-1.amazonaws.com";
        String noSqlCollectionName = "products";

        // Connection default value initialization
        Connection sqlConnection = null;
        MongoClient mongoClient = null;
        try {
            // Creating database connection
            sqlConnection = DriverManager.getConnection(url, user, password);
            mongoClient = MongoClients.create(mongoConnectionString);
            MongoDatabase db = mongoClient.getDatabase(noSqlDBName);



            MongoCollection<Document> collection = db.getCollection(noSqlCollectionName);
            CRUDHelper.importDataToMongoDB(sqlConnection, "mobiles", "Mobile",collection);
            CRUDHelper.importDataToMongoDB(sqlConnection, "cameras", "Camera",collection);
            CRUDHelper.importDataToMongoDB(sqlConnection, "headphones", "Headphone",collection);



            // List all products in the inventory
            CRUDHelper.displayAllProducts(collection);

            // Display top 5 Mobiles
            CRUDHelper.displayTop5Mobiles(collection);

            // Display products ordered by their categories in Descending Order Without autogenerated Id
            CRUDHelper.displayCategoryOrderedProductsDescending(collection);

            // Display product count in each category
            CRUDHelper.displayProductCountByCategory(collection);

            // Display wired headphones
            CRUDHelper.displayWiredHeadphones(collection);
        }
        catch(SQLException ex) {
            System.out.println("Got Exception");
            ex.printStackTrace();
        }
        finally {
            // Close Connections
            if (sqlConnection != null) {
                try {
                    sqlConnection.close();
                } catch (SQLException exception) {
                    exception.printStackTrace();
                }
            }
            }
        }
    }
